changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
      - dependabot[bot]
  categories:
    - title: "New Features"
      labels:
        - enhancement
        - feature
    - title: "Bug Fixes"
      labels:
        - bug
        - fix
    - title: "Documentation"
      labels:
        - documentation
        - docs
    - title: "Maintenance"
      labels:
        - chore
        - maintenance
        - dependencies
    - title: "Other Changes"
      labels:
        - "*"
